-- ══════════════════════════════════════════════════════════════════════════════
-- SUPABASE MIGRATION v5 — Eximple Trade Inquiry Agent
-- Run this in your Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════════════════════

-- 1. Eximple Calls (trade inquiry data)
CREATE TABLE IF NOT EXISTS eximple_calls (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at            TIMESTAMPTZ DEFAULT NOW(),
    phone_number          TEXT,
    caller_name           TEXT,
    duration_seconds      INTEGER,
    transcript            TEXT,
    summary               TEXT,
    sentiment             TEXT,
    estimated_cost_usd    NUMERIC(10,5),
    call_date             DATE,
    call_hour             INTEGER,
    call_day_of_week      TEXT,
    was_booked            BOOLEAN DEFAULT FALSE,
    interrupt_count       INTEGER DEFAULT 0,

    -- Inquiry fields
    email                 TEXT,
    company_name          TEXT,
    services              JSONB,           -- ["Freight Forwarding", "Customs Clearance"]
    license_details       JSONB,           -- [{"type": "License", "name": "IEC"}]
    trade_direction       TEXT,            -- "export" | "import"
    port_of_loading       TEXT,
    port_of_destination   TEXT,
    pickup_address        TEXT,
    drop_off_address      TEXT,
    goods_description     TEXT,
    quantity              NUMERIC,
    quantity_unit         TEXT,
    shipment_value        NUMERIC,
    shipment_currency     TEXT,
    incoterm              TEXT,
    dispatch_date         DATE,
    container_type        TEXT,            -- "FCL" | "LCL"
    fcl_container_details JSONB,           -- [{"container_size": "20ft", "quantity": 1}]
    cargo_weight_kg       NUMERIC,
    cargo_length_cm       NUMERIC,
    cargo_width_cm        NUMERIC,
    cargo_height_cm       NUMERIC,
    cargo_volume_cbm      NUMERIC,
    remarks               TEXT,

    -- Tracking
    inquiry_complete      BOOLEAN DEFAULT FALSE,
    missing_fields        JSONB,           -- ["email", "incoterm"] for incomplete inquiries
    extraction_conflicts  JSONB,           -- [{field, tool_value, transcript_value, used}]
    compliance_status     TEXT DEFAULT 'not_screened'  -- cleared | restricted_item_flagged | permits_claimed | rejected_no_permits | rejected_illegal | not_screened
);

ALTER TABLE eximple_calls ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all_eximple" ON eximple_calls;
CREATE POLICY "allow_all_eximple" ON eximple_calls FOR ALL USING (true) WITH CHECK (true);

-- ══════════════════════════════════════════════════════════════════════════════
-- MIGRATION: If table already exists, run this to add the new column:
-- ALTER TABLE eximple_calls ADD COLUMN IF NOT EXISTS compliance_status TEXT DEFAULT 'not_screened';
-- ══════════════════════════════════════════════════════════════════════════════

-- ══════════════════════════════════════════════════════════════════════════════
-- DONE. Run this once in Supabase SQL Editor.
-- ══════════════════════════════════════════════════════════════════════════════
