-- ══════════════════════════════════════════════════════════════════════════════
-- SUPABASE MIGRATION v4 — Separate tables for each agent
-- Run this in your Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════════════════════

-- 1. Real Estate Calls
CREATE TABLE IF NOT EXISTS real_estate_calls (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMPTZ DEFAULT NOW(),
    phone_number         TEXT,
    caller_name          TEXT,
    duration_seconds     INTEGER,
    transcript           TEXT,
    summary              TEXT,
    sentiment            TEXT,
    estimated_cost_usd   NUMERIC(10,5),
    call_date            DATE,
    call_hour            INTEGER,
    call_day_of_week     TEXT,
    was_booked           BOOLEAN DEFAULT FALSE,
    interrupt_count      INTEGER DEFAULT 0,
    property_preferences TEXT,
    site_visit_time      TEXT
);

ALTER TABLE real_estate_calls ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all_re" ON real_estate_calls;
CREATE POLICY "allow_all_re" ON real_estate_calls FOR ALL USING (true) WITH CHECK (true);

-- 2. Doctor Calls
CREATE TABLE IF NOT EXISTS doctor_calls (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMPTZ DEFAULT NOW(),
    phone_number         TEXT,
    caller_name          TEXT,
    duration_seconds     INTEGER,
    transcript           TEXT,
    summary              TEXT,
    sentiment            TEXT,
    estimated_cost_usd   NUMERIC(10,5),
    call_date            DATE,
    call_hour            INTEGER,
    call_day_of_week     TEXT,
    was_booked           BOOLEAN DEFAULT FALSE,
    interrupt_count      INTEGER DEFAULT 0,
    dental_concern       TEXT,
    appointment_time     TEXT,
    booking_id           TEXT
);

ALTER TABLE doctor_calls ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all_doc" ON doctor_calls;
CREATE POLICY "allow_all_doc" ON doctor_calls FOR ALL USING (true) WITH CHECK (true);

-- 3. Call Transcripts (per-message real-time log)
CREATE TABLE IF NOT EXISTS call_transcripts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMPTZ DEFAULT NOW(),
    call_room_id         TEXT,
    phone                TEXT,
    role                 TEXT,        -- 'user' or 'assistant'
    content              TEXT
);

ALTER TABLE call_transcripts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all_transcripts" ON call_transcripts;
CREATE POLICY "allow_all_transcripts" ON call_transcripts FOR ALL USING (true) WITH CHECK (true);

-- 4. Active Calls (live call tracking — upserted by agents)
CREATE TABLE IF NOT EXISTS active_calls (
    room_id              TEXT PRIMARY KEY,
    phone                TEXT,
    caller_name          TEXT,
    status               TEXT DEFAULT 'active',
    last_updated         TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE active_calls ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all_active" ON active_calls;
CREATE POLICY "allow_all_active" ON active_calls FOR ALL USING (true) WITH CHECK (true);

-- ══════════════════════════════════════════════════════════════════════════════
-- DONE. Run this once in Supabase SQL Editor.
-- ══════════════════════════════════════════════════════════════════════════════

